# Generated by Django 5.1.4 on 2025-01-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('active_ingredients', models.JSONField()),
                ('dosage_form', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('BAR', 'Barcode'), ('SN', 'Serial Number'), ('LOT', 'Lot Number'), ('GTIN', 'Global Trade Item Number'), ('OTHER', 'Other')], max_length=5)),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='api.drug')),
            ],
            options={
                'unique_together': {('code_type', 'value')},
            },
        ),
        migrations.DeleteModel(
            name='DrugInfo',
        ),
    ]
